name: SimpleLightBlock
version: '${project.version}'
main: adhdmc.simplelightblock.SimpleLightBlock
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Making creative light blocks easy to use.
